const http= require("http");

const server= http.createServer(function(request, response){
    //200 sucess, 404 not found , 500 server error
    console.log("Method: ",request.method);
    console.log("URL: ",request.url);

    if(request.url ==="/")
    {
    response.writeHead(200, {"Content-Type":"text/html"});
    response.end(`<h1>Home Page</h1>
        <p>Welcome to our main page!</p>`);
    }
  else if(request.url ==="/contact")
    {
    response.writeHead(200, {"Content-Type":"text/plain"});
    response.end("Please Provide your contact information!");

    }
    else if(request.url ==="/about")
    {
    response.writeHead(200, {"Content-Type":"text/html"});
    response.end(`<h1>About Page</h1>
        <p>This page is generated by Node.js!</p>`);

    }
    else{
      response.writeHead(404, {"Content-Type":"text/plain"});
      response.end("404 - Page not found!")
    }
});
//ports: 3000, 8080, 5000, 443, 80
const port=8080;

server.listen(port);

console.log("Server running at port "+port);